### ISSUE TITLE
[ToDo] Ship this reporter as the ember-cli-mocha default

### ISSUE THREAD

**Issue by ballPointPenguin** [ef4/better-mocha-html-reporter#1]
Per @rwjblue 's suggestion, I will try to make this happen.

**Comment by ef4** [comment]
:+1:

**Comment by carloscheddar** [comment]
:+1:

**Comment by ballPointPenguin** [comment]
Having some trouble with this:
https://github.com/ballPointPenguin/ember-cli-mocha/commit/9ebb73f2a8c874c2afaacf73c7b3c6f1a1b66ce8

**Comment by ballPointPenguin** [comment]
```
$ ember g ember-cli-mocha
version: 1.13.8
installing ember-cli-mocha
  create tests/reporter.js
  identical tests/test-helper.js
event is not defined (Error in blueprint template: /home/brosas/codex/dark-drake/node_modules/ember-cli-mocha/blueprints/ember-cli-mocha/files/tests/reporter.js)
ReferenceError: event is not defined (Error in blueprint template: /home/brosas/codex/dark-drake/node_modules/ember-cli-mocha/blueprints/ember-cli-mocha/files/tests/reporter.js)
    at eval (eval at <anonymous> (/home/brosas/codex/dark-drake/node_modules/ember-cli/node_modules/lodash/string/template.js:214:56), <anonymous>:6:10)
    at processTemplate (/home/brosas/codex/dark-drake/node_modules/ember-cli/lib/models/file-info.js:13:52)
```

**Comment by ballPointPenguin** [comment]
OK, I think it was just blocked by https://github.com/ember-cli/ember-cli/pull/4659

**Comment by NullVoxPopuli** [comment]
any updates on this?
